export * from './About'
export { default as About } from './About'
export * from './Home'
export { default as Home } from './Home'
export * from './Project'
export { default as Project } from './Project'
export * from './Resume'
export { default as Resume } from './Resume'
